Repository SchizzY/next-month-service, pull requests merged in 2024-03, with the labels that each got.

#9 5 setup docker config for both local prod
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  README.md
  compose.yaml
  db/password.txt
  justfile
Labels: documentation, enhancement

#8 7 setup dependabot updates
  .github/dependabot.yml
Labels: enhancement, ci

#11 fix/docker build
  Dockerfile
  compose.yaml
Labels: bug, ci

#15 Fix/docker build
  compose.yaml
  fly.toml
  go.mod
  go.sum
  helper/env.go
  main.go
Labels: enhancement, gomod
